# SPDX-License-Identifier: PMPL-1.0-or-later

[project]
name = "a2ml_ex"
description = "A2ML Elixir implementation"

[container]
base = "cgr.dev/chainguard/wolfi-base:latest"

[build]
builder = "elixir"
